FF 676 - can create integration, configuration, edit, add configs based on version or blank.
FINTLabs/fint-flyt-integration-frontend pull request #99
Opened 2023-03-23 11:53 UTC by ingrie

can also set completed and active and activate from integration panel

2023-03-27 11:23 UTC, ingrie commented on src/context/integrationContext/IntegrationContext.tsx
> +    const [integrations, setIntegrations] = useState<IIntegration[] | undefined>(undefined);
fjerna gammel navnegivning fra når vi splitta integrasjon og konfigurasjon.

2023-03-28 07:02 UTC, ingrie commented on src/features/configuration/components/metadata/MetadataContentComponent.tsx
> +                <div style={{paddingLeft: paddingPerDepth, borderLeft: '1px solid black'}}>
syns det så bedre ut med solid, men er bare et forslag

2023-03-28 08:41 UTC, eivindmorch requested changes

2023-03-28 08:41 UTC, eivindmorch commented on src/features/configuration/components/metadata/MetadataContentComponent.tsx
> +                <div style={{paddingLeft: paddingPerDepth, borderLeft: '1px solid black'}}>
```suggestion
                <div style={{paddingLeft: paddingPerDepth, borderLeft: '1px solid gray'}}>
```

2023-03-28 09:44 UTC, eivindmorch approved these changes

2023-03-28 09:57 UTC, merged